name: ariya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  percent_indicator: ^4.2.3
  supabase: ^2.3.0
  youtube_player_flutter: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/quiz/
    - assets/images/rank/

  fonts:
    - family: SUITE
      fonts:
        - asset: assets/fonts/SUITE-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITE-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITE-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITE-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITE-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITE-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITE-Heavy.ttf
          weight: 900